server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html index.htm;

  resolver 127.0.0.11:53 valid=10s;
  resolver_timeout 5s;
  set $upstream_adminms http://192.168.0.153:6780;
  set $upstream_adminapi http://192.168.0.153:5580;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /springboot-crud-rest-adminms/ {
    proxy_pass $upstream_adminms;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /springboot-crud-rest-admin/ {
    proxy_pass $upstream_adminapi;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

